# Generated by Django 3.2.3 on 2021-07-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=str, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
