# Generated by Django 3.2.3 on 2021-07-22 19:51

from django.db import migrations, models
import django.db.models.deletion
import mroom.common.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210709_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token', models.TextField(default=mroom.common.utils.gen_session_token, unique=True)),
                ('last_active', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
