# Generated by Django 3.2.7 on 2021-12-28 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_barber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
