# Generated by Django 3.2.7 on 2021-12-28 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('date', models.DateTimeField(db_index=True)),
                ('barber', models.CharField(max_length=255)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_barber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
