# Generated by Django 3.2.7 on 2022-01-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment'),
        ('api', '0005_auto_20211228_1109'),
    ]

    operations = [
    ]
