# Generated by Django 3.2.7 on 2021-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_barber',
            field=models.BooleanField(default=False),
        ),
    ]
