# Generated by Django 3.2.7 on 2021-11-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_barber',
        ),
    ]
