# Generated by Django 3.2.7 on 2021-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_is_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_barber',
            field=models.BooleanField(default=False),
        ),
    ]
