# Generated by Django 3.2.7 on 2022-03-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='key',
            field=models.CharField(choices=[('Very_short', 'Very_short'), ('Everyday', 'Everyday'), ('Dandruff', 'Dandruff'), ('Hair_loss', 'Hair_loss'), ('Dry_hair', 'Dry_hair'), ('Psoriasis', 'Psoriasis'), ('Head_lice', 'Head_lice'), ('Bamboo_hair', 'Bamboo_hair'), ('Very_oily_hair', 'Very_oily_hair'), ('EUR', 'EUR'), ('USD', 'USD'), ('Choice_i_dont_know', 'Choice_i_dont_know'), ('Choice_no', 'Choice_no'), ('Choice_yes', 'Choice_yes'), ('Applying_aloe_liquid', 'Applying_aloe_liquid'), ('Applying_lemon', 'Applying_lemon'), ('Applying_garlic_water', 'Applying_garlic_water'), ('Do_not_washing', 'Do_not_washing')], max_length=128),
        ),
    ]
