# Generated by Django 3.2.7 on 2022-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allergies',
            field=models.ManyToManyField(related_name='questions_allergies', to='report.Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='key',
            field=models.CharField(choices=[('Very short', 'Very_short'), ('Everyday', 'Everyday'), ('Dandruff', 'Dandruff'), ('Hair loss', 'Hair_loss'), ('Dry hair', 'Dry_hair'), ('Psoriasis', 'Psoriasis'), ('Head lice', 'Head_lice'), ('Bamboo hair', 'Bamboo_hair'), ('Very oily hair', 'Very_oily_hair'), ('Eur', 'EUR'), ('USD', 'USD'), ("I don't know", 'Choice_i_dont_know'), ('No', 'Choice_no'), ('Yes', 'Choice_yes'), ('Applying aloe liquid', 'Applying_aloe_liquid'), ('Applying lemon', 'Applying_lemon'), ('Applying garlic water', 'Applying_garlic_water'), ('Do not washing', 'Do_not_washing')], max_length=128),
        ),
    ]
