# Generated by Django 3.2.7 on 2022-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20220325_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='allergies',
        ),
        migrations.AddField(
            model_name='question',
            name='solutions',
            field=models.ManyToManyField(related_name='questions_set', to='report.Answer'),
        ),
    ]
