# Generated by Django 3.2.7 on 2022-03-31 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appointment_barber'),
        ('report', '0005_auto_20220325_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='key',
            field=models.CharField(choices=[('very_short', 'Very short'), ('everyday', 'Everyday'), ('dandruff', 'Dandruff'), ('hair_loss', 'Hair loss'), ('dry_hair', 'Dry hair'), ('psoriasis', 'Psoriasis'), ('head_lice', 'Head lice'), ('bamboo_hair', 'Bamboo hair'), ('very_oily', 'Very oily hair'), ('eur', 'EUR'), ('usd', 'USD'), ('idk', "I don't know"), ('no', 'No'), ('yes', 'Yes'), ('aloe_liquid', 'Applying aloe liquid'), ('lemon', 'Applying lemon'), ('garlic_water', 'Applying garlic water'), ('not_washing', 'Do not washing')], max_length=128),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='api.user'),
        ),
    ]
