# Generated by Django 3.2.7 on 2022-04-11 14:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20220331_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='key',
            field=models.CharField(choices=[('default', 'Default survey')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
