# Generated by Django 3.2.7 on 2022-03-31 21:57

from django.db import migrations


def create_survey(apps, schema_editor):
    Answer = apps.get_model('report', 'Answer')
    Question = apps.get_model('report', 'Question')
    Survey = apps.get_model('report', 'Survey')

    survey = Survey.objects.create(key='default')

    questions_answers = [
        {
            'question_name': 'How long hair do you have?',
            'answers': [
                {
                    'name': 'Very short',
                    'description': 'Very_short',
                    'key': 'very_short'
                },
                {
                    'name': 'Short',
                    'description': 'Short',
                    'key': 'short'
                },
                {
                    'name': 'Medium',
                    'description': 'Medium',
                    'key': 'medium'
                },
                {
                    'name': 'Long',
                    'description': 'Long',
                    'key': 'long'
                },

            ]
        },
        {
            'question_name': 'How often do you wash your hair?',
            'answers': [
                {
                    'name': 'Everyday',
                    'description': 'Everyday',
                    'key': 'everyday'
                },
                {
                    'name': '2 times a week',
                    'description': '2_times_a_week',
                    'key': 'two_times'
                },
                {
                    'name': '1 time a week',
                    'description': '1_time_a_week',
                    'key': 'one_time'
                },
                {
                    'name': '3 times a week',
                    'description': '3_times_a_wee',
                    'key': 'three_times'
                },

            ]
        },
        {
            'question_name': 'What kind of problems do you have?',
            'answers': [
                {
                    'name': 'Dandruff',
                    'description': 'Dandruff',
                    'key': 'dandruff'
                },
                {
                    'name': 'Hair loss',
                    'description': 'Hair_loss',
                    'key': 'hair_loss'
                },
                {
                    'name': 'Dry hair',
                    'description': 'Dry_hair',
                    'key': 'dry_hair'
                },
                {
                    'name': 'Psoriasis',
                    'description': 'Psoriasis',
                    'key': 'psoriasis'
                },
                {
                    'name': 'Head lice',
                    'description': 'Head_lice',
                    'key': 'head_lice'
                },
                {
                    'name': 'Bamboo hair',
                    'description': 'Bamboo_hair',
                    'key': 'bamboo_hair'
                },
                {
                    'name': 'Very oily hair',
                    'description': 'Very_oily_hair',
                    'key': 'very_oily'
                },

            ]
        },
        {
            'question_name': 'What is the price for your shampoo?',
            'answers': [
                {
                    'name': 'EUR',
                    'description': 'EUR',
                    'key': 'eur'
                },
                {
                    'name': 'USD',
                    'description': 'USD',
                    'key': 'usd'
                },
            ]
        },
        {
            'question_name': 'Solutions you can do at home',
            'answers': [
                {
                    'name': 'Yes',
                    'description': 'Yes',
                    'key': 'yes'
                },
                {
                    'name': 'No',
                    'description': 'No',
                    'key': 'no'
                },
                {
                    'name': "I don't know",
                    'description': "I don't know",
                    'key': 'idk'
                },
            ],
            'solutions': [
                {
                    'name': 'Applying aloe liquid',
                    'description': 'Applying_aloe_liquid',
                    'key': 'aloe_liquid'
                },
                {
                    'name': 'Applying lemon',
                    'description': 'Applying_lemon',
                    'key': 'lemon'
                },
                {
                    'name': 'Applying garlic water',
                    'description': 'Applying_garlic_water',
                    'key': 'garlic_water'
                },
                {
                    'name': 'Do not washing',
                    'description': 'Do_not_washing',
                    'key': 'not_washing'
                },
            ]
        },
    ]

    for question_answers in questions_answers:
        question = Question.objects.create(
            name=question_answers['question_name']
        )
        for answer in question_answers['answers']:
            question.answers.add(Answer.objects.create(**answer))

        if question_answers['question_name'] == 'Solutions you can do at home':
            for solution in questions_answers[4]['solutions']:
                question.solutions.add(Answer.objects.create(**solution))

        survey.questions.add(question)

class Migration(migrations.Migration):
    dependencies = [
        ('report', '0007_auto_20220411_1748'),
    ]

    operations = [
        migrations.RunPython(create_survey),
    ]
