# Generated by Django 3.2.7 on 2022-03-31 21:57

from django.db import migrations


def create_survey(apps, schema_editor):
    Answer = apps.get_model('report', 'Answer')
    Question = apps.get_model('report', 'Question')
    Survey = apps.get_model('report', 'Survey')

    first_answer_very_short = Answer.objects.create(
        name='Very short',
        description='Very_short',
        key='very_short'
    )
    first_answer_short = Answer.objects.create(
        name='Short',
        description='Short',
        key='short'
    )
    first_answer_medium = Answer.objects.create(
        name='Medium',
        description='Medium',
        key='medium'
    )
    first_answer_long = Answer.objects.create(
        name='Long',
        description='Long',
        key='long'
    )
    second_answer_everyday = Answer.objects.create(
        name='Everyday',
        description='Everyday',
        key='everyday'
    )
    second_answer_two_times = Answer.objects.create(
        name='2 times a week',
        description='2_times_a_week',
        key='two_times'
    )
    second_answer_one_time = Answer.objects.create(
        name='1 time a week',
        description='1_time_a_week',
        key='one_time'
    )
    second_answer_three_times = Answer.objects.create(
        name='3 times a week',
        description='3_times_a_week',
        key='three_times'
    )
    third_answer_dandruff = Answer.objects.create(
        name='Dandruff',
        description='Dandruff',
        key='dandruff'
    )
    third_answer_hair_loss = Answer.objects.create(
        name='Hair loss',
        description='Hair_loss',
        key='hair_loss'
    )
    third_answer_dry_hair = Answer.objects.create(
        name='Dry hair',
        description='Dry_hair',
        key='dry_hair'
    )
    third_answer_psoriasis = Answer.objects.create(
        name='Psoriasis',
        description='Psoriasis',
        key='psoriasis'
    )
    third_answer_head_lice = Answer.objects.create(
        name='Head lice',
        description='Head_lice',
        key='head_lice'
    )
    third_answer_bamboo_hair = Answer.objects.create(
        name='Bamboo hair',
        description='Bamboo_hair',
        key='bamboo_hair'
    )
    third_answer_very_oily_hair = Answer.objects.create(
        name='Very oily hair',
        description='Very_oily_hair',
        key='very_oily'
    )
    fourth_answer_euro = Answer.objects.create(
        name='EUR',
        description='EUR',
        key='eur'
    )
    fourth_answer_usd = Answer.objects.create(
        name='USD',
        description='USD',
        key='usd'
    )
    fifth_answer_yes = Answer.objects.create(
        name='Yes',
        description='Yes',
        key='yes'
    )
    fifth_answer_no = Answer.objects.create(
        name='No',
        description='No',
        key='no'
    )
    fifth_answer_idk = Answer.objects.create(
        name="I don't know",
        description="I don't know",
        key='idk'
    )
    fifth_answer_yes_aloe_liquid = Answer.objects.create(
        name='Applying aloe liquid',
        description='Applying_aloe_liquid',
        key='aloe_liquid'
    )
    fifth_answer_yes_lemon = Answer.objects.create(
        name='Applying lemon',
        description='Applying_lemon',
        key='lemon'
    )
    fifth_answer_yes_garlic_water = Answer.objects.create(
        name='Applying garlic water',
        description='Applying_garlic_water',
        key='garlic_water'
    )
    fifth_answer_yes_not_washing = Answer.objects.create(
        name='Do not washing',
        description='Do_not_washing',
        key='not_washing'
    )
    question_one = Question.objects.create(
        name='How long hair do you have?'
    )
    question_two = Question.objects.create(
        name='How often do you wash your hair?'
    )
    question_three = Question.objects.create(
        name='What kind of problems do you have?'
    )
    question_four = Question.objects.create(
        name='What is the price for your shampoo?'
    )
    question_five = Question.objects.create(
        name='Solutions you can do at home'
    )
    question_one.answers.add(
        first_answer_very_short,
        first_answer_short,
        first_answer_medium,
        first_answer_long
    )
    question_one.save()
    question_two.answers.add(
        second_answer_everyday, second_answer_two_times,
        second_answer_one_time, second_answer_three_times,
    )
    question_two.save()
    question_three.answers.add(
        third_answer_dandruff, third_answer_hair_loss,
        third_answer_dry_hair, third_answer_psoriasis,
        third_answer_head_lice, third_answer_bamboo_hair,
        third_answer_very_oily_hair
    )
    question_three.save()
    question_four.answers.add(
        fourth_answer_euro, fourth_answer_usd,
    )
    question_five.answers.add(
        fifth_answer_yes, fifth_answer_no, fifth_answer_idk,
    )
    question_five.save()
    question_five.solutions.add(
        fifth_answer_yes_aloe_liquid, fifth_answer_yes_lemon,
        fifth_answer_yes_garlic_water, fifth_answer_yes_not_washing
    )
    survey = Survey.objects.create(
        key='default'
    )
    survey.questions.add(
        question_one, question_two,
        question_three, question_four,
        question_five
    )
    survey.save()


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0007_auto_20220411_1748'),
    ]

    operations = [
        migrations.RunPython(create_survey),
    ]
