# Generated by Django 3.2.7 on 2022-06-20 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appointment_barber'),
        ('report', '0008_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(choices=[('how_long_hair', 'How long hair do you have?'), ('how_often_wash', 'How often do you wash your hair?'), ('problems_you_have', 'What kind of problems do you have?'), ('shampoo_price', 'What is the price for your shampoo?'), ('solutions_at_home', 'Solutions you can do at home')], default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
