# Generated by Django 3.2.7 on 2022-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20220620_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.TextField(choices=[('how_long_hair', 'How long hair do you have?'), ('how_often_wash', 'How often do you wash your hair?'), ('problems_you_have', 'What kind of problems do you have?'), ('shampoo_price', 'What is the price for your shampoo?'), ('solutions_at_home', 'Solutions you can do at home')]),
        ),
    ]
