# Generated by Django 3.2.7 on 2022-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20220620_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
